kuch_baatein = "dear Larib,\nyou will never be able to \"see\" the light of the sun!!\n \tahahhahahah"
print(kuch_baatein)

lamhein = "suna ley meri baat,\royee" #\r jitna words ka hoga utna woh replace kar dega
print(lamhein)

text = "This is an octal: \101"  # Represents 'A'
print(text)


'''escape sequnces
\n  next line
\t  tab sapce
\r  return carriage
\'
\"
\\  backslash
\000 octal value'''